# Generated by Django 4.1.3 on 2023-04-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miniforum.thread'),
            preserve_default=False,
        ),
    ]
